/* ClauseFinder — offline rule reader + full-text search */
'use strict';

const $  = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const esc = s => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const rxEsc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/* Where things live - see cf-config.js. The defaults below are the LOCAL ones,
   so the app still runs if that file is missing. */
const CFG = Object.assign(
  { dataBase: 'data/', apiBase: 'api/', semantic: 'server', noStore: true },
  window.CF_CONFIG || {});

const dataUrl = p => CFG.dataBase + p;
const apiUrl  = p => CFG.apiBase + p;

// Locally the rule data is regenerated by build/build.js while the app may be
// open, so it must never come from the browser cache - a stale books.json
// silently hides whole rule books. Online the data is immutable and the cache
// is the whole point: without it every reload re-downloads an 11 MB index.
const fetchOpts = () => (CFG.noStore ? { cache: 'no-store' } : {});

const getJSON = u => fetch(u, fetchOpts()).then(r => { if (!r.ok) throw new Error(r.status); return r.json(); });
const getText = u => fetch(u, fetchOpts()).then(r => { if (!r.ok) throw new Error(r.status); return r.text(); });

const LS = {
  get(k, d) { try { const v = localStorage.getItem('cf.' + k); return v == null ? d : JSON.parse(v); } catch (e) { return d; } },
  set(k, v) { try { localStorage.setItem('cf.' + k, JSON.stringify(v)); } catch (e) {} }
};

const S = {
  books: [],            // registry from books.json
  lib: new Map(),       // bookId -> {meta, toc, secMap, secList, clauses, figures}
  book: null,           // current book meta (reader)
  cur: null,            // current section id
  recent: [],
  q: null,              // active query object (drives reader highlighting)
  qRaw: '',
  marks: [], markAt: -1,
  scope: 'book',     // what search + Ask look at: 'book' | 'society' | 'all' | 'node'
  scopeNode: null    // when scope==='node': { book, id, label, secs:[sectionId] }
};

/* ══════════════════════════════ boot ══════════════════════════════ */

async function boot() {
  applyTheme(LS.get('theme', 'dark'));
  S.scope = LS.get('scope', 'book');
  bindGlobal();
  progress(20);

  if (location.protocol === 'file:') {
    $('#doc').innerHTML = `<div class="welcome">
      <div class="w-badge" style="color:var(--warn);background:rgba(245,158,11,.12);border-color:rgba(245,158,11,.35)">Wrong way in</div>
      <h2>Start ClauseFinder with its launcher</h2>
      <p>Opening <code>index.html</code> straight from the file system leaves the browser unable to read the
      rule data next to it. Close this tab and double-click <b>ClauseFinder.bat</b> in the same folder instead.</p></div>`;
    progress(100); return;
  }
  try {
    // Online the CDN caches every object for a year - right for the immutable
    // book files, wrong for the registry once a book is added. dataVersion in
    // cf-config bumps the URL so a new registry is fetched; per-book files are
    // new keys anyway.
    S.books = await getJSON(dataUrl('books.json' + (CFG.dataVersion ? '?v=' + CFG.dataVersion : '')));
    if (!Array.isArray(S.books) || !S.books.length) throw new Error('empty');
  } catch (e) {
    $('#doc').innerHTML = `<div class="welcome">
      <div class="w-badge" style="color:var(--warn);background:rgba(245,158,11,.12);border-color:rgba(245,158,11,.35)">No data</div>
      <h2>The rule data has not been built yet</h2>
      <p>Run <code>node build/build.js</code> in the ClauseFinder folder, then reload.</p></div>`;
    progress(100); return;
  }

  const wanted = LS.get('book', null);
  const b = S.books.find(x => x.id === wanted) || S.books[0];
  await setBook(b.id);
  progress(100);
  route();
  window.addEventListener('hashchange', route);

  // warm every index while the reader is idle — search spans all books
  const warm = () => Promise.all(S.books.map(x => ensureIndex(x.id).catch(() => {})));
  if (typeof requestIdleCallback === 'function') requestIdleCallback(warm, { timeout: 5000 });
  else setTimeout(warm, 1500);
}

async function ensureBook(id) {
  if (S.lib.has(id)) return S.lib.get(id);
  const meta = S.books.find(b => b.id === id);
  const data = await getJSON(dataUrl(`${id}/toc.json`));
  const secMap = new Map(), secList = [];
  for (const p of data.toc)
    for (const c of p.chapters)
      for (const s of c.sections) {
        const rec = { ...s, part: p, chap: c, book: meta };
        secMap.set(s.id, rec); secList.push(rec);
      }
  secList.sort((a, b) => a.order - b.order);
  const entry = { meta, toc: data.toc, secMap, secList, clauses: null, figures: null };
  S.lib.set(id, entry);
  return entry;
}

// Concurrent callers share one download; a failure clears the slot so the next
// call retries instead of leaving that book silently missing from every search.
const inflight = new Map();
function ensureIndex(id) {
  const done = S.lib.get(id);
  if (done && done.clauses) return Promise.resolve(done);
  if (inflight.has(id)) return inflight.get(id);
  const p = (async () => {
    const e = await ensureBook(id);
    if (e.clauses) return e;
    const [cl, fg] = await Promise.all([
      getJSON(dataUrl(`${id}/search.json`)),
      getJSON(dataUrl(`${id}/figures.json`)).catch(() => [])
    ]);
    for (const c of cl) { c.lt = c.t.toLowerCase(); c.b = id; }
    e.clauses = cl;
    e.figures = fg.map(f => ({ ...f, b: id, ll: (f.l + ' ' + (f.t || '')).toLowerCase() }));
    return e;
  })();
  p.catch(() => {}).then(() => inflight.delete(id));
  inflight.set(id, p);
  return p;
}
/* The picker works in two steps: pick the class society, then pick among the
   books we actually hold for that class. */
const societyOf = b => b.society || (b.code || '').split(/[-\s]/)[0].toUpperCase();
const societies = () => [...new Set(S.books.map(societyOf))];
const booksOf = soc => S.books.filter(b => societyOf(b) === soc);

/* Search and Ask read this, not the whole library: answering a DNV question out of
   an LR clause is worse than not answering, and a 5-book pool dilutes the top-k. */
function scopedBooks() {
  if (S.scope === 'all' || !S.book) return S.books;
  if (S.scope === 'node' && S.scopeNode) return S.books.filter(b => b.id === S.scopeNode.book);
  if (S.scope === 'society') return booksOf(societyOf(S.book));
  return S.books.filter(b => b.id === S.book.id);
}

/* A Set of section ids when the scope is narrowed to one part or chapter of the
   tree, null when the whole book (or more) is in play.  Kept separate from
   scopedBooks so every retriever can apply it the same way. */
function scopedSections() {
  return S.scope === 'node' && S.scopeNode ? S.scopeNode.set : null;
}

/* Collect the sections under a part, or under one chapter of it. */
function sectionsUnder(bookId, partId, chapId) {
  const e = S.lib.get(bookId); if (!e) return [];
  const out = [];
  for (const p of e.toc) {
    if (p.id !== partId) continue;
    for (const c of p.chapters) {
      if (chapId && c.id !== chapId) continue;
      for (const sec of c.sections) out.push(sec.id);
    }
  }
  return out;
}

function clearNodeScope() {
  S.scope = 'book'; S.scopeNode = null;
  LS.set('scope', 'book'); LS.set('scopeNode', null);
  renderScope(); renderTree($('#navFilter') ? $('#navFilter').value : '');
  toast('Searching ' + (S.book ? S.book.short : 'this book') + ' again');
}

/* Scope can be a part, a chapter or a single section - the same machinery, only
   the set of sections differs. */
function applyNodeScope(bookId, id, secs, label, saved) {
  if (!secs.length) return false;
  S.scope = 'node';
  S.scopeNode = { book: bookId, id, label, secs, set: new Set(secs) };
  LS.set('scope', 'node');
  LS.set('scopeNode', Object.assign({ book: bookId, label }, saved));
  renderScope();
  toast('Searching ' + label + ' only — ' + secs.length + ' section' + (secs.length > 1 ? 's' : ''));
  return true;
}

function setNodeScope(bookId, partId, chapId, label) {
  return applyNodeScope(bookId, chapId || partId, sectionsUnder(bookId, partId, chapId), label,
                        { part: partId, chap: chapId || '' });
}

function setSectionScope(bookId, secId, label) {
  return applyNodeScope(bookId, secId, [secId], label, { sec: secId });
}

const missingBooks = () => S.books.filter(b => !(S.lib.get(b.id) || {}).clauses);
const allIndexed = () => missingBooks().length === 0;

async function setBook(id) {
  const e = await ensureBook(id);
  S.book = e.meta;
  LS.set('book', id);
  S.recent = LS.get('recent.' + id, []);

  if (S.scope === 'node' && (!S.scopeNode || S.scopeNode.book !== id)) { S.scope = 'book'; S.scopeNode = null; }
  S.society = societyOf(e.meta);
  $('#classCode').textContent = S.society;
  $('#classPick').title = e.meta.publisher;
  $('#bookCode').textContent = e.meta.code;
  $('#bookName').textContent = `${e.meta.short} · ${e.meta.edition}`;
  $('#brandSub').textContent = `${e.meta.publisher} — ${e.meta.title}`;
  $('#chipStats').textContent = `${e.meta.sections} sections · ${e.meta.clauses.toLocaleString('en')} clauses`;
  document.title = `ClauseFinder — ${e.meta.short}`;
  // a branch scope saved from a previous session only makes sense once the
  // book's contents tree is loaded, so it is restored here rather than at boot
  if (S.scope === 'node' && !S.scopeNode) {
    const saved = LS.get('scopeNode', null);
    if (saved && saved.book === id) {
      const secs = saved.sec ? (e.secMap.has(saved.sec) ? [saved.sec] : [])
                             : sectionsUnder(saved.book, saved.part, saved.chap || '');
      if (secs.length) S.scopeNode = { book: saved.book, id: saved.sec || saved.chap || saved.part,
                                       label: saved.label, secs, set: new Set(secs) };
    }
    if (!S.scopeNode) S.scope = 'book';
  }
  renderScope();
  renderTree();
  return e;
}
const cur = () => S.lib.get(S.book.id);

/* ══════════════════════════════ tree ══════════════════════════════ */

/* the magnifier that narrows search to one branch of the tree */
const SCOPE_ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/></svg>';

function renderTree(filter) {
  const e = cur(); if (!e) return;
  const q = (filter || '').trim().toLowerCase();
  const open = LS.get('open', {});
  let html = '';

  for (const p of e.toc) {
    let chaps = '';
    for (const c of p.chapters) {
      const secs = c.sections.filter(s => !q ||
        s.label.toLowerCase().includes(q) || (c.title || '').toLowerCase().includes(q) ||
        (p.title || '').toLowerCase().includes(q) || p.label.toLowerCase().includes(q));
      if (!secs.length) continue;
      const rows = secs.map(s => {
        const sScoped = S.scope === 'node' && S.scopeNode && S.scopeNode.id === s.id;
        return `<div class="t-rowwrap${sScoped ? ' scoped' : ''}">
          <button class="t-sec${S.cur === s.id ? ' cur' : ''}" data-sec="${s.id}">
            <span class="num">${esc(s.no || '·')}</span><span class="nm">${hl(s.title || s.label, q)}</span>
          </button>
          <button class="t-scope" data-scope-sec="${s.id}" title="Search only in this section">${SCOPE_ICON}</button>
        </div>`;
      }).join('');
      const co = q ? true : !!open['c' + c.id];
      const cScoped = S.scope === 'node' && S.scopeNode && S.scopeNode.id === c.id;
      chaps += c.label
        ? `<div class="t-chap${co ? ' open' : ''}" data-ck="c${c.id}">
             <div class="t-rowwrap${cScoped ? ' scoped' : ''}">
               <button class="t-row${co ? ' open' : ''}" data-toggle="chap">
                 <svg class="tw" viewBox="0 0 16 16"><path d="M6 4l4 4-4 4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>
                 <span class="num">Ch ${c.n}</span><span class="nm">${hl(c.title || c.label, q)}</span>
               </button>
               <button class="t-scope" data-scope-part="${p.id}" data-scope-chap="${c.id}"
                 title="Search only in this chapter">${SCOPE_ICON}</button>
             </div><div class="t-secs">${rows}</div></div>`
        : `<div class="t-secs" style="display:block;border:0;margin:0;padding:0">${rows}</div>`;
    }
    if (!chaps) continue;
    const po = q ? true : !!open['p' + p.id];
    const pScoped = S.scope === 'node' && S.scopeNode && S.scopeNode.id === p.id;
    html += `<div class="t-part${po ? ' open' : ''}" data-pk="p${p.id}">
      <div class="t-rowwrap${pScoped ? ' scoped' : ''}">
        <button class="t-row${po ? ' open' : ''}" data-toggle="part">
          <svg class="tw" viewBox="0 0 16 16"><path d="M6 4l4 4-4 4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>
          <span class="num">${esc(p.label.replace('Part ', 'Pt ').replace('Chapter ', 'Ch '))}</span>
          <span class="nm">${hl(p.title, q)}</span>
        </button>
        <button class="t-scope" data-scope-part="${p.id}" title="Search only in this part">${SCOPE_ICON}</button>
      </div><div class="t-chaps">${chaps}</div></div>`;
  }
  $('#tree').innerHTML = html || `<div class="t-empty">Nothing matches “${esc(q)}”</div>`;
}

function hl(text, q) {
  if (!q) return esc(text);
  const i = String(text).toLowerCase().indexOf(q);
  if (i < 0) return esc(text);
  return esc(text.slice(0, i)) + '<mark>' + esc(text.slice(i, i + q.length)) + '</mark>' + esc(text.slice(i + q.length));
}

/* ══════════════════════════════ query engine ══════════════════════════════ */

const NUM_RE = /^\d+(\.\d+){0,4}\.?$/;

function parseQuery(raw, whole) {
  const phrases = [], excl = [];
  let rest = String(raw || '');
  rest = rest.replace(/-"([^"]+)"/g, (m, p) => { excl.push(p.toLowerCase().trim()); return ' '; });
  rest = rest.replace(/"([^"]+)"/g, (m, p) => { phrases.push(p.toLowerCase().trim()); return ' '; });
  rest = rest.replace(/(^|\s)-([^\s]+)/g, (m, sp, w) => { excl.push(w.toLowerCase()); return ' '; });
  const tokens = rest.toLowerCase().split(/[^a-z0-9µΔσετ°.\-_/]+/i).filter(t => t.length > 1);
  const nums = tokens.filter(t => NUM_RE.test(t)).map(t => t.replace(/\.$/, ''));
  const words = tokens.filter(t => !NUM_RE.test(t));
  const terms = [...phrases, ...words];
  return { raw: String(raw || '').trim(), phrases, words, nums, excl, terms, whole: !!whole,
           empty: !phrases.length && !words.length && !nums.length };
}

// every position where any term occurs, merged and sorted
function findHits(lt, q) {
  const out = [];
  for (const t of q.terms) {
    if (!t) continue;
    let i = 0;
    while ((i = lt.indexOf(t, i)) !== -1) {
      const okL = !q.whole || i === 0 || !/[a-z0-9]/.test(lt[i - 1]);
      const okR = !q.whole || i + t.length >= lt.length || !/[a-z0-9]/.test(lt[i + t.length]);
      if (okL && okR) out.push([i, t.length]);
      i += Math.max(1, t.length);
      if (out.length > 400) break;
    }
  }
  out.sort((a, b) => a[0] - b[0]);
  const merged = [];
  for (const h of out) {
    const last = merged[merged.length - 1];
    if (last && h[0] <= last[0] + last[1]) last[1] = Math.max(last[1], h[0] + h[1] - last[0]);
    else merged.push(h.slice());
  }
  return merged;
}

function scoreClause(c, q) {
  if (q.excl.some(x => c.lt.includes(x))) return null;
  let sc = 0, numHit = false;
  for (const n of q.nums) {
    if (c.n === n) { sc += 400; numHit = true; }
    else if (c.n && c.n.startsWith(n + '.')) { sc += 120; numHit = true; }
    else if (c.lt.includes(n)) sc += 8;
  }
  const hits = q.terms.length ? findHits(c.lt, q) : [];
  if (q.phrases.length) {
    for (const p of q.phrases) if (!c.lt.includes(p)) return null;
    sc += 90 * q.phrases.length;
  }
  if (q.words.length) {
    let miss = 0;
    for (const w of q.words) {
      const i = c.lt.indexOf(w);
      if (i < 0) { miss++; continue; }
      sc += 16 + (i < 110 ? 8 : 0);
    }
    if (miss === q.words.length && !numHit) return null;
    if (!miss) sc += 40;                       // all words present
    else if (!numHit && miss > 0 && q.words.length > 1) sc -= miss * 22;
  }
  if (!hits.length && !numHit) return null;
  sc += Math.min(hits.length, 6) * 4;
  if (c.h) sc += 10;                            // headings rank a little higher
  sc += proximityBonus(c.lt, q.words);          // terms sitting together beat terms scattered
  return { c, sc, hits };
}

// smallest window containing one occurrence of every word — tight windows score much higher
function proximityBonus(lt, words) {
  if (words.length < 2) return 0;
  const pos = words.map(w => {
    const a = []; let i = 0;
    while ((i = lt.indexOf(w, i)) !== -1) { a.push(i); i += w.length; if (a.length > 60) break; }
    return a;
  });
  if (pos.some(a => !a.length)) return 0;
  const idx = pos.map(() => 0);
  let best = Infinity;
  for (;;) {
    let mn = Infinity, mx = -1, mi = 0;
    for (let k = 0; k < pos.length; k++) {
      const v = pos[k][idx[k]];
      if (v < mn) { mn = v; mi = k; }
      if (v > mx) mx = v;
    }
    best = Math.min(best, mx - mn);
    if (++idx[mi] >= pos[mi].length) break;
  }
  return best <= 70 ? 90 : best <= 180 ? 45 : best <= 400 ? 15 : 0;
}

async function runSearch(q, filters) {
  if (q.empty) return { groups: [], total: 0, facets: null };
  for (let attempt = 0; attempt < 2 && !allIndexed(); attempt++)
    await Promise.all(missingBooks().map(b => ensureIndex(b.id).catch(() => {})));
  const pending = missingBooks();

  const raw = [];
  for (const b of S.books) {
    const e = S.lib.get(b.id); if (!e || !e.clauses) continue;
    for (const c of e.clauses) {
      const r = scoreClause(c, q);
      if (r) raw.push(r);
    }
  }

  // facet counts are computed before filtering so the numbers stay meaningful
  const fBook = new Map(), fPart = new Map(), fType = new Map();
  const bump = (m, k, lbl) => { const o = m.get(k) || { k, lbl, n: 0 }; o.n++; m.set(k, o); };
  const decorate = r => {
    const e = S.lib.get(r.c.b);
    r.sec = e.secMap.get(r.c.s);
    return r.sec;
  };
  for (const r of raw) {
    if (!decorate(r)) continue;
    bump(fBook, r.c.b, S.lib.get(r.c.b).meta.short);
    bump(fPart, r.c.b + '|' + r.sec.part.id, r.sec.part.label + ' ' + (r.sec.part.title || ''));
    bump(fType, r.c.h ? 'heading' : 'clause', r.c.h ? 'Headings' : 'Clauses');
  }

  const keep = raw.filter(r => r.sec
    && (!filters.book.size || filters.book.has(r.c.b))
    && (!filters.part.size || filters.part.has(r.c.b + '|' + r.sec.part.id))
    && (!filters.type.size || filters.type.has(r.c.h ? 'heading' : 'clause')));

  // group by section
  const gm = new Map();
  for (const r of keep) {
    const k = r.c.b + '|' + r.c.s;
    let g = gm.get(k);
    if (!g) { g = { key: k, book: S.lib.get(r.c.b).meta, sec: r.sec, hits: [], top: 0 }; gm.set(k, g); }
    g.hits.push(r);
    if (r.sc > g.top) g.top = r.sc;
  }
  const groups = [...gm.values()];
  for (const g of groups) {
    g.hits.sort((a, b) => cmpClause(a.c.n, b.c.n));
    // a section whose own title carries the query is almost always what was wanted
    const hay = (g.sec.label + ' ' + (g.sec.chap.title || '') + ' ' + (g.sec.part.title || '')).toLowerCase();
    let tb = 0;
    for (const w of q.words) if (hay.includes(w)) tb += 55;
    if (q.words.length > 1 && q.words.every(w => hay.includes(w))) tb += 170;
    if (q.words.length > 1 && hay.includes(q.words.join(' '))) tb += 260;
    for (const p of q.phrases) if (hay.includes(p)) tb += 260;
    g.titleBoost = tb;
    g.score = g.top + tb + Math.min(g.hits.length, 8) * 4;
  }
  if (filters.sort === 'doc') {
    const bi = id => S.books.findIndex(b => b.id === id);
    groups.sort((a, b) => bi(a.book.id) - bi(b.book.id) || a.sec.order - b.sec.order);
  } else {
    groups.sort((a, b) => b.score - a.score || a.sec.order - b.sec.order);
  }
  return { groups, total: keep.length, allTotal: raw.length, pending,
           facets: { book: [...fBook.values()], part: [...fPart.values()].sort((a, b) => b.n - a.n),
                     type: [...fType.values()] } };
}

function cmpClause(a, b) {
  const pa = String(a || '').split('.').map(Number), pb = String(b || '').split('.').map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const x = pa[i] || 0, y = pb[i] || 0;
    if (x !== y) return x - y;
  }
  return String(a).localeCompare(String(b));
}

/* ── sentence-aware context ───────────────────────────────────────── */

const SENT_END = /[.;:!?]\s/g;
function sentenceWindow(text, at, len, before = 1, after = 1) {
  let start = 0, end = text.length;
  // walk back over `before` sentence boundaries
  let idx = at, found = 0;
  while (idx > 0 && found <= before) {
    const cut = lastBoundary(text, idx);
    if (cut < 0) { start = 0; break; }
    found++; idx = cut;
    if (found > before) { start = cut; break; }
    start = cut;
  }
  idx = at + len; found = 0;
  while (idx < text.length && found <= after) {
    SENT_END.lastIndex = idx;
    const m = SENT_END.exec(text);
    if (!m) { end = text.length; break; }
    found++; idx = m.index + m[0].length; end = idx;
    if (found > after) break;
  }
  if (at - start > 320) start = at - 320;
  if (end - (at + len) > 340) end = at + len + 340;
  return [Math.max(0, start), Math.min(text.length, end)];
}
function lastBoundary(text, from) {
  for (let i = from - 2; i > 0; i--) {
    if (/[.;:!?]/.test(text[i]) && /\s/.test(text[i + 1])) return i + 2;
  }
  return -1;
}

// renders the clause text with every hit marked, cropped to a readable window
function contextHtml(text, hits) {
  if (!hits.length) return esc(text.slice(0, 260)) + (text.length > 260 ? ' …' : '');
  const [s0, e0] = sentenceWindow(text, hits[0][0], hits[0][1]);
  let s = s0, e = e0;
  for (const h of hits) {                       // stretch to cover nearby hits too
    if (h[0] < e + 220 && h[0] + h[1] > e) e = Math.min(text.length, h[0] + h[1] + 140);
  }
  let out = '', pos = s;
  for (const [i, l] of hits) {
    if (i + l <= s || i >= e) continue;
    if (i > pos) out += esc(text.slice(pos, i));
    out += '<mark>' + esc(text.slice(i, i + l)) + '</mark>';
    pos = i + l;
  }
  out += esc(text.slice(pos, e));
  return (s > 0 ? '<span class="lead">… </span>' : '') + out + (e < text.length ? '<span class="tail"> …</span>' : '');
}

/* ══════════════════════════════ search view ══════════════════════════════ */

const SV = { q: null, res: null, filters: null, shown: 40, sel: -1, flat: [] };

function searchHash(raw, f) {
  const p = new URLSearchParams();
  p.set('q', raw);
  if (f.book.size) p.set('b', [...f.book].join(','));
  if (f.part.size) p.set('p', [...f.part].join(','));
  if (f.type.size) p.set('t', [...f.type].join(','));
  if (f.sort !== 'rel') p.set('s', f.sort);
  if (f.whole) p.set('w', '1');
  return '#/search?' + p.toString();
}
function goSearch(raw, f) {
  const flt = f || SV.filters || newFilters();
  location.hash = searchHash(raw, flt);
}
const newFilters = () => ({ book: new Set(), part: new Set(), type: new Set(), sort: 'rel', whole: false });

async function openSearch(params) {
  const raw = params.get('q') || '';
  const f = newFilters();
  (params.get('b') || '').split(',').filter(Boolean).forEach(x => f.book.add(x));
  (params.get('p') || '').split(',').filter(Boolean).forEach(x => f.part.add(x));
  (params.get('t') || '').split(',').filter(Boolean).forEach(x => f.type.add(x));
  f.sort = params.get('s') === 'doc' ? 'doc' : 'rel';
  f.whole = params.get('w') === '1';

  document.body.classList.add('mode-search');
  $('#searchview').hidden = false;
  $('#matchbar').hidden = true;
  $('#sq').value = raw;
  $('#sqClear').hidden = !raw;
  $('#svWhole').checked = f.whole;
  $$('.seg').forEach(b => b.classList.toggle('active', b.dataset.sort === f.sort));
  SV.filters = f;
  SV.q = parseQuery(raw, f.whole);
  S.q = SV.q; S.qRaw = raw;

  if (SV.q.empty) { paintEmpty(raw); return; }

  $('#svResults').innerHTML = '<div class="skel"><div></div><div></div><div></div><div></div><div></div></div>';
  $('#svCount').textContent = 'searching…';
  progress(40);
  SV.res = await runSearch(SV.q, f);
  SV.shown = 40; SV.sel = -1;
  progress(100);
  paintSearch();
  rememberQuery(raw);
}

function paintEmpty(raw) {
  $('#svCount').textContent = '';
  $('#svFacets').innerHTML = '';
  const hist = LS.get('queries', []).slice(0, 8);
  $('#svResults').innerHTML = `<div class="sv-empty">
    <div class="big">${raw ? 'Type at least two characters' : 'Search every rule book at once'}</div>
    <p style="font-size:12.5px;max-width:60ch;margin:0 auto 18px">Words are combined with AND. Wrap an exact
    phrase in <code>"quotes"</code>, drop a term with <code>-word</code>, or type a clause number
    like <code>6.3.2</code> to jump straight to it.</p>
    ${hist.length ? '<div style="font-size:11.5px;color:var(--tx-3);margin-bottom:8px">Recent searches</div>' +
      hist.map(h => `<button class="seg" style="margin:3px" data-again="${esc(h)}">${esc(h)}</button>`).join('') : ''}
  </div>`;
}

function paintSearch() {
  const { groups, total, allTotal, facets } = SV.res;
  const nSec = groups.length;
  $('#svCount').innerHTML = total
    ? `<b>${total.toLocaleString('en')}</b> match${total === 1 ? '' : 'es'} in <b>${nSec}</b> section${nSec === 1 ? '' : 's'}` +
      (allTotal > total ? ` <span style="color:var(--tx-3)">(${allTotal.toLocaleString('en')} before filters)</span>` : '')
    : 'no matches';
  $('#svSyntax').innerHTML = SV.q.phrases.length || SV.q.excl.length || SV.q.nums.length
    ? [SV.q.phrases.length ? 'phrase' : '', SV.q.excl.length ? 'exclusion' : '', SV.q.nums.length ? 'clause number' : '']
        .filter(Boolean).map(x => `<code>${x}</code>`).join(' ')
    : '<code>"phrase"</code><code>-exclude</code><code>6.3.2</code>';

  if (SV.res.pending && SV.res.pending.length) {
    $('#svCount').innerHTML += ` <span style="color:var(--warn)">· ${esc(SV.res.pending.map(b => b.short).join(', '))} still loading…</span>`;
    Promise.all(SV.res.pending.map(b => ensureIndex(b.id).catch(() => {})))
      .then(() => { if (SV.q && SV.q.raw === $('#sq').value.trim()) goSearch($('#sq').value, SV.filters); });
  }

  paintFacets(facets);

  if (!groups.length) {
    $('#svResults').innerHTML = `<div class="sv-empty">
      <div class="big">Nothing found for “${esc(SV.q.raw)}”</div>
      <p style="font-size:12.5px">Try fewer words, turn off <b>Whole words</b>, or clear the filters on the left.</p>
    </div>`;
    return;
  }

  const slice = groups.slice(0, SV.shown);
  SV.flat = [];
  let html = '';
  for (const g of slice) {
    const open = g.hits.length <= 12;
    const shownHits = g.hits.slice(0, 5);
    html += `<article class="grp${open ? ' open' : ''}" data-g="${esc(g.key)}">
      <button class="grp-head" data-toggle="grp">
        <svg class="grp-tw" viewBox="0 0 16 16"><path d="M6 4l4 4-4 4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>
        <span class="grp-main">
          <span class="grp-crumb"><span class="bk">${esc(g.book.short)}</span><i>›</i>${crumbOf(g.sec)}</span>
          <span class="grp-title">${esc(g.sec.title || g.sec.label)}</span>
        </span>
        <span class="grp-n">${g.hits.length}</span>
        <span class="grp-open" data-open="${esc(g.book.id)}|${esc(g.sec.id)}">Open section</span>
      </button>
      <div class="grp-hits">`;
    for (const r of shownHits) {
      const i = SV.flat.length;
      SV.flat.push({ b: g.book.id, s: g.sec.id, a: r.c.a });
      html += `<button class="hit" data-i="${i}">
        <span class="hit-no${r.c.h ? ' head' : ''}">${esc(r.c.n || (r.c.h ? '§' : '¶'))}</span>
        <span class="hit-body">${contextHtml(r.c.t, r.hits)}${
          r.hits.length > 1 ? `<span class="hit-more">${r.hits.length} occurrences in this clause</span>` : ''}</span>
      </button>`;
    }
    if (g.hits.length > shownHits.length)
      html += `<button class="grp-rest" data-rest="${esc(g.key)}">Show the other ${g.hits.length - shownHits.length} matches in this section</button>`;
    html += `</div></article>`;
  }
  if (groups.length > SV.shown)
    html += `<button class="sv-more" id="svMore">Load the next ${Math.min(40, groups.length - SV.shown)} sections
      <span style="color:var(--tx-3)">(${groups.length - SV.shown} left)</span></button>`;
  $('#svResults').innerHTML = html;
}

const crumbOf = s => {
  const bits = [];
  if (s.part && s.part.label) bits.push(esc(s.part.label.replace('Part ', 'Pt ').replace('Chapter ', 'Ch ')));
  if (s.chap && s.chap.label) bits.push(esc(s.chap.label.replace('Chapter ', 'Ch ')));
  bits.push(esc(s.label.replace('Section ', 'Sec ')));
  return bits.join('<i>›</i>');
};

function paintFacets(f) {
  if (!f) { $('#svFacets').innerHTML = ''; return; }
  const F = SV.filters;
  const grp = (title, key, rows, cap) => {
    if (rows.length < 2 && key !== 'book') return '';
    return `<div class="fgroup"><h5>${title}</h5>` + rows.slice(0, cap).map(r =>
      `<button class="frow${F[key].has(r.k) ? ' on' : ''}" data-facet="${key}" data-k="${esc(r.k)}">
         <span class="fn">${esc(r.lbl)}</span><span class="fc">${r.n}</span></button>`).join('') + '</div>';
  };
  const any = F.book.size || F.part.size || F.type.size;
  $('#svFacets').innerHTML =
    grp('Rule book', 'book', f.book, 10) +
    grp('Part / chapter', 'part', f.part, 14) +
    grp('Kind', 'type', f.type, 4) +
    (any ? '<button class="fclear" id="fClear">Clear all filters</button>' : '');
}

function rememberQuery(raw) {
  if (!raw || raw.length < 2) return;
  const h = LS.get('queries', []).filter(x => x !== raw);
  h.unshift(raw); LS.set('queries', h.slice(0, 20));
}

function moveHit(d) {
  const n = SV.flat.length; if (!n) return;
  SV.sel = SV.sel < 0 ? (d > 0 ? 0 : n - 1) : (SV.sel + d + n) % n;
  $$('.hit').forEach((el, i) => el.classList.toggle('sel', i === SV.sel));
  const el = $('.hit.sel'); if (el) el.scrollIntoView({ block: 'nearest' });
}
function openHit(i) {
  const h = SV.flat[i != null ? i : SV.sel];
  if (h) go(h.b, h.s, h.a);
}

/* ══════════════════════════════ reader ══════════════════════════════ */

function route() {
  const h = location.hash.replace(/^#\/?/, '');
  if (h.startsWith('search')) {
    const qs = h.indexOf('?');
    openSearch(new URLSearchParams(qs >= 0 ? h.slice(qs + 1) : ''));
    return;
  }
  document.body.classList.remove('mode-search');
  $('#searchview').hidden = true;
  if (!h) { showWelcome(); return; }
  const [bookId, secId, anchor] = h.split('/');
  if (bookId && S.books.some(b => b.id === bookId)) {
    const after = () => secId ? openSection(secId, anchor) : showWelcome();
    if (!S.book || bookId !== S.book.id) setBook(bookId).then(after); else after();
  } else showWelcome();
}

function go(bookId, secId, anchor) {
  // Telefonda gezinti bir cekmece: bir bolume dokununca kapanir, yoksa
  // secilen bolum cekmecenin arkasinda kalir.
  cekmeceKapat();
  const target = `#/${bookId}/${secId}${anchor ? '/' + anchor : ''}`;
  if (location.hash === target) { scrollToAnchor(anchor); return; }
  location.hash = target;
}

function showWelcome() {
  S.cur = null;
  $('#pager').hidden = true;
  $('#matchbar').hidden = true;
  $('#crumb').innerHTML = '';
  $('#doc').innerHTML = '';
  $('#doc').appendChild(buildWelcome());
  $('#outlineList').innerHTML = '<div class="o-empty">Open a section to see its clauses.</div>';
  $$('.t-sec.cur').forEach(e => e.classList.remove('cur'));
}

function buildWelcome() {
  const t = document.createElement('div');
  t.className = 'welcome';
  t.innerHTML = `
    <div class="w-badge">Offline rule reader</div>
    <h2>Search the rules, or press <kbd>Ctrl</kbd><kbd>K</kbd></h2>
    <p id="welcomeSub"></p>
    <div class="w-cards" id="welcomeCards"></div>
    <div class="w-recent" id="welcomeRecent"></div>`;
  setTimeout(renderWelcome, 0);
  return t;
}

function renderWelcome() {
  const m = S.book; if (!m || !$('#welcomeCards')) return;
  const tot = S.books.reduce((a, b) => ({ s: a.s + b.sections, c: a.c + b.clauses, i: a.i + b.images }), { s: 0, c: 0, i: 0 });
  $('#welcomeSub').textContent =
    `${S.books.length} rule book${S.books.length > 1 ? 's' : ''} indexed offline — full text, figures and formulae, every internal cross-reference wired up.`;
  $('#welcomeCards').innerHTML = [
    [tot.s.toLocaleString('en'), 'sections'], [tot.c.toLocaleString('en'), 'clauses'],
    [tot.i.toLocaleString('en'), 'figures &amp; formulae'], ['0', 'broken links']
  ].map(([n, l]) => `<div class="w-card"><b>${n}</b><span>${l}</span></div>`).join('');
  drawRecent();
}

function drawRecent() {
  const box = $('#welcomeRecent'); if (!box) return;
  const e = cur();
  const list = S.recent.filter(id => e.secMap.has(id)).slice(0, 6);
  box.innerHTML = list.length ? '<h4>Recently opened</h4>' + list.map(id => {
    const s = e.secMap.get(id);
    return `<button data-sec="${id}"><em>${esc(plainCrumb(s))}</em><span>${esc(s.title || s.label)}</span></button>`;
  }).join('') : '';
}
const plainCrumb = s => [s.part && s.part.label, s.chap && s.chap.label, s.label]
  .filter(Boolean).map(x => x.replace('Part ', 'Pt ').replace('Chapter ', 'Ch ').replace('Section ', 'Sec ')).join(' · ');

async function openSection(id, anchor) {
  const e = cur();
  const rec = e.secMap.get(id);
  if (!rec) { toast('Section not found'); return; }
  if (S.cur === id) { scrollToAnchor(anchor); return; }

  progress(30);
  $('#doc').innerHTML = '<div class="skel"><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>';
  let html;
  try { html = await getText(dataUrl(`${S.book.id}/sections/${id}.html`)); }
  catch (err) { toast('Could not load that section'); return; }
  progress(70);

  const paint = () => {
    S.cur = id;
    const doc = $('#doc');
    doc.innerHTML = html;
    doc.querySelectorAll('img[src^="img/"]').forEach(im =>
      im.setAttribute('src', dataUrl(`${S.book.id}/`) + im.getAttribute('src')));
    drawCrumb(rec);
    drawOutline();
    drawPager(rec);
    $$('.t-sec').forEach(el => el.classList.toggle('cur', el.dataset.sec === id));
    revealInTree(id);
    remember(id);
    applyHighlight();
  };

  if (document.startViewTransition && !document.hidden) {
    try {
      const vt = document.startViewTransition(paint);
      await Promise.race([vt.finished.catch(() => {}), new Promise(r => setTimeout(r, 700))]);
    } catch (err) { paint(); }
  } else paint();

  $('#reader').scrollTop = 0;
  if (anchor) scrollToAnchor(anchor); else if (S.marks.length) jumpMark(0);
  progress(100);
}

function scrollToAnchor(anchor) {
  if (!anchor) return;
  setTimeout(() => {
    const el = document.getElementById(anchor);
    if (!el) return;
    el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    el.classList.remove('flash'); void el.offsetWidth; el.classList.add('flash');
    const inside = S.marks.findIndex(m => el.contains(m));
    if (inside >= 0) jumpMark(inside, true);
  }, 30);
}

function remember(id) {
  S.recent = [id, ...S.recent.filter(x => x !== id)].slice(0, 12);
  LS.set('recent.' + S.book.id, S.recent);
}

function revealInTree(id) {
  const btn = $(`.t-sec[data-sec="${CSS.escape(id)}"]`); if (!btn) return;
  const chap = btn.closest('.t-chap'), part = btn.closest('.t-part');
  const open = LS.get('open', {});
  if (part) { part.classList.add('open'); part.querySelector('.t-row').classList.add('open'); open[part.dataset.pk] = true; }
  if (chap) { chap.classList.add('open'); chap.querySelector('.t-row').classList.add('open'); open[chap.dataset.ck] = true; }
  LS.set('open', open);
  const r = btn.getBoundingClientRect(), nr = $('#tree').getBoundingClientRect();
  if (r.top < nr.top + 20 || r.bottom > nr.bottom - 20) btn.scrollIntoView({ block: 'center', behavior: 'smooth' });
}

function drawCrumb(s) {
  $('#crumb').innerHTML =
    `<a href="#" data-home="1">${esc(S.book.short)}</a><i>›</i>` +
    (s.part && s.part.label ? `<span>${esc(s.part.label)} ${esc(s.part.title || '')}</span><i>›</i>` : '') +
    (s.chap && s.chap.label ? `<span>${esc(s.chap.label)} ${esc(s.chap.title || '')}</span><i>›</i>` : '') +
    `<span class="cur">${esc(s.label)}</span>`;
}

function drawOutline() {
  const heads = $$('#doc h2, #doc h3');
  const list = $('#outlineList');
  if (!heads.length) { list.innerHTML = '<div class="o-empty">No sub-headings in this section.</div>'; return; }
  list.innerHTML = heads.map((h, i) => {
    if (!h.dataset.oid) h.dataset.oid = 'o' + i;
    const pre = h.querySelector('.prefix');
    const num = pre ? pre.textContent.trim() : '';
    const nm = h.textContent.replace(num, '').trim();
    return `<button class="o-item${h.tagName === 'H3' ? ' lvl2' : ''}" data-oid="${h.dataset.oid}">
      <span class="num">${esc(num || '·')}</span><span class="nm">${esc(nm)}</span></button>`;
  }).join('');
  spy();
}

let spyTick;
function spy() {
  const heads = $$('#doc h2, #doc h3'); if (!heads.length) return;
  const top = $('#reader').scrollTop + 90;
  let c = heads[0];
  for (const h of heads) { if (h.offsetTop <= top) c = h; else break; }
  $$('.o-item').forEach(b => b.classList.toggle('cur', b.dataset.oid === c.dataset.oid));
}

function drawPager(s) {
  const e = cur();
  const i = e.secList.findIndex(x => x.id === s.id);
  const prev = e.secList[i - 1], next = e.secList[i + 1];
  $('#pager').hidden = false;
  $('#prevSec').disabled = !prev; $('#nextSec').disabled = !next;
  $('#prevLabel').textContent = prev ? prev.label : '';
  $('#nextLabel').textContent = next ? next.label : '';
  $('#prevSec').dataset.sec = prev ? prev.id : '';
  $('#nextSec').dataset.sec = next ? next.id : '';
}

/* ── highlight the active query inside the open section ───────────── */

function applyHighlight() {
  S.marks = []; S.markAt = -1;
  const bar = $('#matchbar');
  const terms = S.q && !S.q.empty ? S.q.terms.filter(t => t.length > 1) : [];
  if (!terms.length) { bar.hidden = true; return; }

  const rx = new RegExp('(' + terms.sort((a, b) => b.length - a.length).map(rxEsc).join('|') + ')',
    S.q.whole ? 'gi' : 'gi');
  const walker = document.createTreeWalker($('#doc'), NodeFilter.SHOW_TEXT, {
    acceptNode: n => (n.nodeValue && n.nodeValue.trim() && !/^(SCRIPT|STYLE|MARK)$/.test(n.parentNode.nodeName))
      ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT
  });
  const targets = [];
  let n; while ((n = walker.nextNode())) if (rx.test(n.nodeValue)) { rx.lastIndex = 0; targets.push(n); }

  for (const node of targets) {
    const parts = node.nodeValue.split(rx);
    if (parts.length < 2) continue;
    const frag = document.createDocumentFragment();
    parts.forEach((p, i) => {
      if (!p) return;
      if (i % 2) {
        if (S.q.whole) {
          const prev = parts[i - 1] || '', next = parts[i + 1] || '';
          if (/[a-z0-9]$/i.test(prev) || /^[a-z0-9]/i.test(next)) { frag.appendChild(document.createTextNode(p)); return; }
        }
        const m = document.createElement('mark');
        m.className = 'q'; m.textContent = p;
        frag.appendChild(m); S.marks.push(m);
      } else frag.appendChild(document.createTextNode(p));
    });
    node.parentNode.replaceChild(frag, node);
  }

  if (!S.marks.length) { bar.hidden = true; return; }
  $('#mbTerm').textContent = S.qRaw;
  bar.hidden = false;
  updateMarkCount();
}
function updateMarkCount() {
  $('#mbCount').textContent = (S.markAt < 0 ? '—' : (S.markAt + 1)) + ' / ' + S.marks.length;
}
function jumpMark(i, quiet) {
  if (!S.marks.length) return;
  S.marks.forEach(m => m.classList.remove('cur'));
  S.markAt = ((i % S.marks.length) + S.marks.length) % S.marks.length;
  const m = S.marks[S.markAt];
  m.classList.add('cur');
  if (!quiet) m.scrollIntoView({ behavior: 'smooth', block: 'center' });
  updateMarkCount();
}
function clearHighlight() {
  S.q = null; S.qRaw = ''; S.marks = []; S.markAt = -1;
  $('#matchbar').hidden = true;
  $$('#doc mark.q').forEach(m => { const t = document.createTextNode(m.textContent); m.parentNode.replaceChild(t, m); });
}

/* ══════════════════════════════ command palette ══════════════════════════════ */

const P = { open: false, scope: 'all', items: [], sel: 0, q: null };

async function openPalette(seed) {
  P.open = true;
  $('#palette').hidden = false;
  $('#pq').value = seed != null ? seed : (S.qRaw || '');
  $('#pq').focus(); $('#pq').select();
  if (!allIndexed()) { $('#pcount').textContent = 'indexing…'; await Promise.all(S.books.map(b => ensureIndex(b.id).catch(() => {}))); }
  runPalette();
}
function closePalette() { P.open = false; $('#palette').hidden = true; }

function runPalette() {
  const raw = $('#pq').value;
  P.q = parseQuery(raw, false);
  P.items = [];
  if (raw.trim().length >= 2) P.items.push({ kind: 'action', raw });

  if (!raw.trim()) {
    const e = cur();
    P.items = S.recent.filter(id => e.secMap.has(id)).slice(0, 8)
      .map(id => ({ kind: 'section', s: e.secMap.get(id) }));
    $('#pcount').textContent = '';
    paintPalette('Recent'); return;
  }
  if (!P.q.empty) {
    const secOnly = scopedSections();
    for (const b of scopedBooks()) {
      const e = S.lib.get(b.id); if (!e) continue;
      if (P.scope === 'all' || P.scope === 'section')
        for (const s of e.secList) {
          if (secOnly && !secOnly.has(s.id)) continue;
          const hay = (s.label + ' ' + (s.chap.title || '') + ' ' + (s.part.title || '')).toLowerCase();
          if (P.q.terms.length && P.q.terms.every(t => hay.includes(t))) P.items.push({ kind: 'section', s, sc: 30 });
        }
      if ((P.scope === 'all' || P.scope === 'figure') && e.figures)
        for (const f of e.figures) {
          if (secOnly && !secOnly.has(f.s)) continue;
          if (P.q.terms.some(t => f.ll.includes(t)) || P.q.nums.some(nn => f.l.includes(nn)))
            P.items.push({ kind: 'figure', f, book: b, sec: e.secMap.get(f.s), sc: 20 });
        }
      if ((P.scope === 'all' || P.scope === 'clause') && e.clauses)
        for (const c of e.clauses) {
          if (secOnly && !secOnly.has(c.s)) continue;
          const r = scoreClause(c, P.q);
          if (r) P.items.push({ kind: 'clause', c, hits: r.hits, sc: r.sc, sec: e.secMap.get(c.s), book: b });
        }
    }
    const head = P.items[0] && P.items[0].kind === 'action' ? P.items.shift() : null;
    P.items.sort((a, b) => (b.sc || 0) - (a.sc || 0));
    P.items = P.items.slice(0, 60);
    if (head) { head.n = P.items.length; P.items.unshift(head); }
  }
  P.sel = 0;
  $('#pcount').textContent = P.items.length > 1 ? `${P.items.length - 1}+ quick results` : '';
  paintPalette();
}

function paintPalette(groupLabel) {
  const list = $('#plist');
  if (!P.items.length) {
    list.innerHTML = `<div class="p-empty">Nothing found.<br><span style="font-size:11.5px">
      Try a clause number like <code>6.3.2</code>, or wrap an exact phrase in quotes.</span></div>`;
    return;
  }
  let html = '', lastKind = null;
  P.items.forEach((it, i) => {
    if (it.kind === 'action') {
      html += `<button class="p-item p-action${i === P.sel ? ' sel' : ''}" data-i="${i}">
        <span class="p-badge">↵</span><span class="p-main">
        <span class="p-title">Search all rule books for “${esc(it.raw)}”</span>
        <span class="p-path">Opens the full results page with context and filters</span></span>
        <kbd class="p-kbd">Enter</kbd></button>`;
      return;
    }
    const kind = groupLabel || ({ section: 'Sections', clause: 'Clauses', figure: 'Figures & formulae' })[it.kind];
    if (kind !== lastKind) { html += `<div class="p-group">${esc(kind)}</div>`; lastKind = kind; }
    html += `<button class="p-item${i === P.sel ? ' sel' : ''}" data-i="${i}">${rowHtml(it)}</button>`;
  });
  list.innerHTML = html;
  const s = $('.p-item.sel'); if (s) s.scrollIntoView({ block: 'nearest' });
}

function rowHtml(it) {
  if (it.kind === 'section') {
    const s = it.s;
    return `<span class="p-badge">${esc(s.no ? 'Sec ' + s.no : '§')}</span>
      <span class="p-main"><span class="p-title">${esc(s.title || s.label)}</span>
      <span class="p-path">${esc(s.book.short)} · ${esc(plainCrumb(s))}</span></span>`;
  }
  if (it.kind === 'clause') {
    return `<span class="p-badge">${esc(it.c.n || '¶')}</span>
      <span class="p-main"><span class="p-sub">${contextHtml(it.c.t, (it.hits || []).slice(0, 2))}</span>
      <span class="p-path">${it.sec ? esc(it.book.short + ' · ' + plainCrumb(it.sec)) : ''}</span></span>`;
  }
  const f = it.f;
  return `<span class="p-badge">${/^Figure/i.test(f.l) ? 'FIG' : 'EQ'}</span>
    <span class="p-main"><span class="p-title">${esc(f.l)}</span>
    ${f.t ? `<span class="p-sub" style="font-family:var(--f-mono)">${esc(f.t)}</span>` : ''}
    <span class="p-path">${it.sec ? esc(it.book.short + ' · ' + plainCrumb(it.sec)) : ''}</span></span>`;
}

function movePal(d) {
  const n = P.items.length; if (!n) return;
  P.sel = (P.sel + d + n) % n;
  $$('.p-item').forEach((e, i) => e.classList.toggle('sel', i === P.sel));
  const s = $('.p-item.sel'); if (s) s.scrollIntoView({ block: 'nearest' });
}
function activate(i) {
  const it = P.items[i != null ? i : P.sel]; if (!it) return;
  closePalette();
  if (it.kind === 'action') { goSearch(it.raw, newFilters()); return; }
  if (it.kind === 'section') { S.q = P.q; S.qRaw = $('#pq').value; go(it.s.book.id, it.s.id); return; }
  if (it.kind === 'clause') { S.q = P.q; S.qRaw = $('#pq').value; go(it.c.b, it.c.s, it.c.a); return; }
  go(it.f.b, it.f.s);
}

/* ══════════════════════════════ misc ══════════════════════════════ */

function applyTheme(t) { document.documentElement.dataset.theme = t; LS.set('theme', t); }
let toastT;
function toast(msg) {
  const el = $('#toast'); el.textContent = msg; el.hidden = false;
  clearTimeout(toastT); toastT = setTimeout(() => el.hidden = true, 2200);
}
let progT;
function progress(v) {
  const el = $('#progress');
  el.style.opacity = '1'; el.style.width = v + '%';
  clearTimeout(progT);
  if (v >= 100) progT = setTimeout(() => { el.style.opacity = '0'; el.style.width = '0'; }, 320);
}
function openLightbox(img) {
  $('#lbImg').src = img.src; $('#lbImg').alt = img.alt || '';
  $('#lbLabel').textContent = img.alt || 'Figure';
  const txt = img.getAttribute('title') || '';
  $('#lbText').textContent = txt; $('#lbText').hidden = !txt; $('#lbCopy').hidden = !txt;
  $('#lightbox').hidden = false;
}
function debounce(fn, ms) { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); }; }

/* ══════════════════════════════ events ══════════════════════════════ */

/* ── telefon: gezinti cekmecesi ──
   Masaustunde gezinti hep acik; bu uc fonksiyon yalnizca 720 px altinda
   anlam tasir (CSS orada .nav'i cekmeceye ceviriyor). Masaustunde cagrilmalari
   zararsiz - body.nav-open sinifinin orada hicbir kurali yok. */
const TELEFON = () => window.matchMedia('(max-width:720px)').matches;
function cekmeceAc() {
  document.body.classList.add('nav-open');
  const b = $('#navBtn'); if (b) b.setAttribute('aria-expanded', 'true');
}
function cekmeceKapat() {
  if (!document.body.classList.contains('nav-open')) return;
  document.body.classList.remove('nav-open');
  const b = $('#navBtn'); if (b) b.setAttribute('aria-expanded', 'false');
}

function bindGlobal() {
  $('#navBtn')?.addEventListener('click', () =>
    document.body.classList.contains('nav-open') ? cekmeceKapat() : cekmeceAc());
  $('#navBackdrop')?.addEventListener('click', cekmeceKapat);
  // Telefonda Escape once cekmeceyi kapatsin (asagidaki genel Escape
  // kurallarindan once, capture asamasinda).
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape' && TELEFON() && document.body.classList.contains('nav-open')) { cekmeceKapat(); e.stopPropagation(); }
  }, true);
  $('#tree').addEventListener('click', e => {
    // narrow the search to this branch
    const sc = e.target.closest('[data-scope-part]');
    if (sc) {
      e.stopPropagation();
      const partId = sc.dataset.scopePart, chapId = sc.dataset.scopeChap || '';
      const already = S.scope === 'node' && S.scopeNode && S.scopeNode.id === (chapId || partId);
      if (already) { clearNodeScope(); return; }
      const en = cur();
      const part = en.toc.find(x => x.id === partId);
      const chap = chapId && part ? part.chapters.find(x => x.id === chapId) : null;
      const label = part
        ? (chap ? part.label + ' · ' + chap.label : part.label + ' ' + (part.title || ''))
        : partId;
      setNodeScope(S.book.id, partId, chapId, label.trim());
      renderTree($('#navFilter').value);
      return;
    }
    const ss = e.target.closest('[data-scope-sec]');
    if (ss) {
      e.stopPropagation();
      const id = ss.dataset.scopeSec;
      if (S.scope === 'node' && S.scopeNode && S.scopeNode.id === id) { clearNodeScope(); return; }
      const en = cur(), meta = en && en.secMap.get(id);
      const label = meta ? [meta.part.label, meta.chap.label, meta.label].filter(Boolean).join(' · ') : id;
      setSectionScope(S.book.id, id, label);
      renderTree($('#navFilter').value);
      return;
    }
    const sec = e.target.closest('[data-sec]');
    if (sec) { go(S.book.id, sec.dataset.sec); return; }
    const row = e.target.closest('[data-toggle]'); if (!row) return;
    const box = row.closest('[data-pk],[data-ck]');
    if (!box) return;
    box.classList.toggle('open'); row.classList.toggle('open');
    const open = LS.get('open', {}); const k = box.dataset.pk || box.dataset.ck;
    if (k) { open[k] = box.classList.contains('open'); LS.set('open', open); }
  });

  $('#navFilter').addEventListener('input', e => { renderTree(e.target.value); $('#navClear').hidden = !e.target.value; });
  $('#navClear').addEventListener('click', () => { $('#navFilter').value = ''; $('#navClear').hidden = true; renderTree(); });
  $('#expandAll').addEventListener('click', () => {
    const open = LS.get('open', {});
    $$('.t-part,.t-chap').forEach(b => { b.classList.add('open'); b.querySelector('.t-row').classList.add('open'); open[b.dataset.pk || b.dataset.ck] = true; });
    LS.set('open', open);
  });
  $('#collapseAll').addEventListener('click', () => {
    $$('.t-part,.t-chap').forEach(b => { b.classList.remove('open'); b.querySelector('.t-row').classList.remove('open'); });
    LS.set('open', {});
  });

  /* ── search view ── */
  const rerun = debounce(() => goSearch($('#sq').value, SV.filters), 260);
  $('#sq').addEventListener('input', () => { $('#sqClear').hidden = !$('#sq').value; rerun(); });
  $('#sq').addEventListener('keydown', e => {
    if (e.key === 'Enter') { e.preventDefault(); goSearch($('#sq').value, SV.filters); }
    if (e.key === 'ArrowDown') { e.preventDefault(); $('#sq').blur(); moveHit(1); }
  });
  $('#sqClear').addEventListener('click', () => { $('#sq').value = ''; $('#sqClear').hidden = true; goSearch('', newFilters()); $('#sq').focus(); });
  $('#svWhole').addEventListener('change', e => { SV.filters.whole = e.target.checked; goSearch($('#sq').value, SV.filters); });
  $('.sv-sort').addEventListener('click', e => {
    const b = e.target.closest('.seg'); if (!b) return;
    SV.filters.sort = b.dataset.sort; goSearch($('#sq').value, SV.filters);
  });
  $('#svFacets').addEventListener('click', e => {
    if (e.target.closest('#fClear')) { goSearch($('#sq').value, { ...newFilters(), sort: SV.filters.sort, whole: SV.filters.whole }); return; }
    const b = e.target.closest('[data-facet]'); if (!b) return;
    const set = SV.filters[b.dataset.facet];
    set.has(b.dataset.k) ? set.delete(b.dataset.k) : set.add(b.dataset.k);
    goSearch($('#sq').value, SV.filters);
  });
  $('#svResults').addEventListener('click', e => {
    const again = e.target.closest('[data-again]');
    if (again) { goSearch(again.dataset.again, newFilters()); return; }
    const openBtn = e.target.closest('[data-open]');
    if (openBtn) { const [b, s] = openBtn.dataset.open.split('|'); go(b, s); e.stopPropagation(); return; }
    const rest = e.target.closest('[data-rest]');
    if (rest) { expandGroup(rest.dataset.rest); return; }
    const head = e.target.closest('[data-toggle="grp"]');
    if (head) { head.closest('.grp').classList.toggle('open'); return; }
    const hit = e.target.closest('.hit');
    if (hit) { openHit(+hit.dataset.i); return; }
    if (e.target.closest('#svMore')) { SV.shown += 40; paintSearch(); return; }
  });

  /* ── reader ── */
  document.addEventListener('click', e => {
    if (e.target.closest('[data-home]')) { e.preventDefault(); location.hash = ''; return; }
    const rec = e.target.closest('.w-recent [data-sec]');
    if (rec) { go(S.book.id, rec.dataset.sec); return; }
    const anch = e.target.closest('#doc [data-anchor]');
    if (anch) { e.preventDefault(); scrollToAnchor(anch.dataset.anchor); return; }
    const oi = e.target.closest('.o-item');
    if (oi) { const h = $$('#doc h2, #doc h3').find(x => x.dataset.oid === oi.dataset.oid); if (h) h.scrollIntoView({ behavior: 'smooth', block: 'start' }); return; }
    const img = e.target.closest('#doc img'); if (img) { openLightbox(img); return; }
    if (e.target.closest('.brokenlink, .xref-dead')) { toast('That reference points outside this rule set'); return; }
    const p = e.target.closest('.p-item'); if (p) { activate(+p.dataset.i); return; }
  });

  $('#reader').addEventListener('scroll', () => {
    $('#crumb').classList.toggle('stuck', $('#reader').scrollTop > 4);
    clearTimeout(spyTick); spyTick = setTimeout(spy, 90);
  });
  $('#prevSec').addEventListener('click', e => e.currentTarget.dataset.sec && go(S.book.id, e.currentTarget.dataset.sec));
  $('#nextSec').addEventListener('click', e => e.currentTarget.dataset.sec && go(S.book.id, e.currentTarget.dataset.sec));
  $('#goHome').addEventListener('click', () => location.hash = '');

  /* ── match navigator ── */
  $('#mbNext').addEventListener('click', () => jumpMark(S.markAt + 1));
  $('#mbPrev').addEventListener('click', () => jumpMark(S.markAt - 1));
  $('#mbClear').addEventListener('click', clearHighlight);
  $('#mbBack').addEventListener('click', () => S.qRaw ? goSearch(S.qRaw, SV.filters) : history.back());

  /* ── palette ── */
  $('#omniBtn').addEventListener('click', () => openPalette());
  $('#paletteScrim').addEventListener('click', closePalette);
  $('#pq').addEventListener('input', debounce(runPalette, 110));
  $('#pscopes').addEventListener('click', e => {
    const b = e.target.closest('.scope'); if (!b) return;
    P.scope = b.dataset.scope;
    $$('.scope').forEach(x => x.classList.toggle('active', x === b));
    runPalette();
  });

  /* ── picker: class society first, then that class's books ── */
  function closeMenus() { $('#classMenu').hidden = true; $('#bookMenu').hidden = true; $('#scopeMenu').hidden = true; }

  function openBookMenu() {
    const m = $('#bookMenu');
    const list = booksOf(S.society);
    m.innerHTML = list.length
      ? list.map(b => `<button data-book="${b.id}" class="${b.id === S.book.id ? 'on' : ''}">`
        + `<b>${esc(b.short)} — ${esc(b.edition)}</b>`
        + `<span>${esc(b.code)} · ${b.sections} sections · ${b.clauses.toLocaleString('en')} clauses</span></button>`).join('')
      : `<div class="menu-empty">No rules held for ${esc(S.society)} yet.</div>`;
    closeMenus();
    m.hidden = false;
  }

  window.renderScope = function renderScope() {
    const n = scopedBooks().length;
    $('#scopeVal').textContent =
      S.scope === 'node' && S.scopeNode ? S.scopeNode.label
      : S.scope === 'all' ? `all ${S.books.length} books`
      : S.scope === 'society' ? `all ${societyOf(S.book)} (${n})`
      : (S.book ? S.book.short : 'this book');
    $('#scopePick').classList.toggle('narrow', S.scope === 'node');
  };

  function openScopeMenu() {
    const m = $('#scopeMenu');
    const soc = societyOf(S.book), sib = booksOf(soc);
    const rows = [];
    if (S.scope === 'node' && S.scopeNode) rows.push([
      'node', `${esc(S.scopeNode.label)}`,
      `${S.scopeNode.secs.length} section${S.scopeNode.secs.length > 1 ? 's' : ''} · picked from the contents tree`]);
    rows.push([
      'book', `This book — ${esc(S.book.short)}`,
      `${S.book.sections} sections · ${S.book.clauses.toLocaleString('en')} clauses`]);
    if (sib.length > 1) rows.push([
      'society', `All ${esc(soc)} rules`,
      `${sib.length} rule sets · ${sib.reduce((a, b) => a + b.clauses, 0).toLocaleString('en')} clauses`]);
    rows.push([
      'all', `Every book`,
      `${S.books.length} books · ${S.books.reduce((a, b) => a + b.clauses, 0).toLocaleString('en')} clauses`]);
    m.innerHTML = rows.map(([v, t, sub]) =>
      `<button data-scope-lib="${v}" class="${v === S.scope ? 'on' : ''}"><b>${t}</b><span>${sub}</span></button>`).join('');
    closeMenus();
    m.hidden = false;
  }

  $('#scopePick').addEventListener('click', () => {
    if (!$('#scopeMenu').hidden) { $('#scopeMenu').hidden = true; return; }
    openScopeMenu();
  });

  $('#scopeMenu').addEventListener('click', e => {
    const b = e.target.closest('[data-scope-lib]'); if (!b) return;
    $('#scopeMenu').hidden = true;
    if (b.dataset.scopeLib === 'node') return;          // already there
    S.scope = b.dataset.scopeLib;
    S.scopeNode = null; LS.set('scopeNode', null);
    LS.set('scope', S.scope);
    renderScope(); renderTree($('#navFilter').value);
    toast(S.scope === 'book' ? `Searching ${S.book.short} only`
      : S.scope === 'society' ? `Searching all ${societyOf(S.book)} rules`
      : `Searching all ${S.books.length} books`);
  });

  $('#classPick').addEventListener('click', () => {
    const m = $('#classMenu');
    if (!m.hidden) { m.hidden = true; return; }
    m.innerHTML = societies().map(soc => {
      const bs = booksOf(soc);
      return `<button data-society="${esc(soc)}" class="${soc === S.society ? 'on' : ''}">`
        + `<b>${esc(soc)} — ${esc(bs[0].publisher)}</b>`
        + `<span>${bs.length} ${bs.length === 1 ? 'rule set' : 'rule sets'}</span></button>`;
    }).join('');
    closeMenus();
    m.hidden = false;
  });

  $('#classMenu').addEventListener('click', async e => {
    const el = e.target.closest('[data-society]'); if (!el) return;
    const soc = el.dataset.society;
    $('#classMenu').hidden = true;
    const list = booksOf(soc);
    if (!list.length) return;
    if (societyOf(S.book) !== soc) {
      await setBook(list[0].id);
      location.hash = ''; showWelcome();
    }
    S.society = soc;
    // step two: show what this class has, unless there is nothing to choose between
    if (list.length > 1) openBookMenu();
  });

  $('#bookPick').addEventListener('click', () => {
    if (!$('#bookMenu').hidden) { $('#bookMenu').hidden = true; return; }
    openBookMenu();
  });

  $('#bookMenu').addEventListener('click', async e => {
    const b = e.target.closest('[data-book]'); if (!b) return;
    $('#bookMenu').hidden = true;
    if (b.dataset.book !== S.book.id) { await setBook(b.dataset.book); location.hash = ''; showWelcome(); }
  });

  document.addEventListener('click', e => {
    if (!e.target.closest('.pickers')) closeMenus();
  }, true);

  $('#lbScrim').addEventListener('click', () => $('#lightbox').hidden = true);
  $('#lbCopy').addEventListener('click', () => navigator.clipboard.writeText($('#lbText').textContent).then(() => toast('Copied')));
  $('#helpBtn').addEventListener('click', () => $('#help').hidden = false);
  $('#helpScrim').addEventListener('click', () => $('#help').hidden = true);
  $('#themeBtn').addEventListener('click', () => applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'));

  let drag = false;
  $('#navResize').addEventListener('mousedown', () => { drag = true; document.body.style.cursor = 'col-resize'; });
  window.addEventListener('mousemove', e => {
    if (!drag) return;
    document.documentElement.style.setProperty('--nav-w', Math.min(460, Math.max(200, e.clientX)) + 'px');
  });
  window.addEventListener('mouseup', () => { drag = false; document.body.style.cursor = ''; });

  /* ── keyboard ── */
  window.addEventListener('keydown', e => {
    const typing = /^(INPUT|TEXTAREA)$/.test(e.target.tagName);
    const inSearch = document.body.classList.contains('mode-search');

    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); P.open ? closePalette() : openPalette(); return; }
    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'f') { e.preventDefault(); inSearch ? $('#sq').select() : openPalette(); return; }

    if (P.open) {
      if (e.key === 'Escape') { e.preventDefault(); closePalette(); }
      else if (e.key === 'ArrowDown') { e.preventDefault(); movePal(1); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); movePal(-1); }
      else if (e.key === 'Enter') { e.preventDefault(); activate(); }
      return;
    }
    if (e.key === 'Escape') {
      if (!$('#lightbox').hidden) { $('#lightbox').hidden = true; return; }
      if (!$('#help').hidden) { $('#help').hidden = true; return; }
      if (!$('#matchbar').hidden) { clearHighlight(); return; }
      if (typing) { e.target.blur(); return; }
    }

    if (inSearch && !typing) {
      if (e.key === 'ArrowDown' || e.key === 'j') { e.preventDefault(); moveHit(1); return; }
      if (e.key === 'ArrowUp' || e.key === 'k') { e.preventDefault(); moveHit(-1); return; }
      if (e.key === 'Enter') { e.preventDefault(); openHit(); return; }
      if (e.key === '/') { e.preventDefault(); $('#sq').select(); return; }
    }
    if (typing) return;

    if (!inSearch && S.marks.length && e.key === 'Enter') { e.preventDefault(); jumpMark(S.markAt + (e.shiftKey ? -1 : 1)); return; }
    if (e.key === '/') { e.preventDefault(); $('#navFilter').focus(); }
    else if (e.key === '[') { const b = $('#prevSec'); if (!b.disabled && !inSearch) b.click(); }
    else if (e.key === ']') { const b = $('#nextSec'); if (!b.disabled && !inSearch) b.click(); }
    else if (e.key.toLowerCase() === 't') $('#themeBtn').click();
    else if (e.key.toLowerCase() === 'b') document.body.classList.toggle('nav-hidden');
    else if (e.key === '?') $('#help').hidden = false;
  });
}

function expandGroup(key) {
  const g = SV.res.groups.find(x => x.key === key); if (!g) return;
  const box = $(`.grp[data-g="${CSS.escape(key)}"] .grp-hits`); if (!box) return;
  let html = '';
  for (const r of g.hits) {
    const i = SV.flat.length;
    SV.flat.push({ b: g.book.id, s: g.sec.id, a: r.c.a });
    html += `<button class="hit" data-i="${i}">
      <span class="hit-no${r.c.h ? ' head' : ''}">${esc(r.c.n || (r.c.h ? '§' : '¶'))}</span>
      <span class="hit-body">${contextHtml(r.c.t, r.hits)}${
        r.hits.length > 1 ? `<span class="hit-more">${r.hits.length} occurrences in this clause</span>` : ''}</span>
    </button>`;
  }
  box.innerHTML = html;
  box.closest('.grp').classList.add('open');
}

boot();
